### ISSUE TITLE
Add option to skip lines

### ISSUE THREAD

**Issue by joshwapohlmann** [firefly-iii/import-configurations#17]
The bank I'm working with happens to export files with some information in the header before actually starting with the data. It would be nice to have a option to tell the importer to skip some lines in the beginning.

**Comment by joshwapohlmann** [comment]
Example 

```
"Kreditkarte:";"1234****5677";
  
"Zeitraum:";"letztes Jahr";
"Saldo:";"0 EUR";
"Datum:";"01.01.2019";

"Umsatz abgerechnet und nicht im Saldo enthalten";"Wertstellung";"Belegdatum";"Beschreibung";"Betrag (EUR)";"Ursprünglicher Betrag";
"Nein";"02.01.2019";"31.12.2018";"DESCRIPTION";"-35,00";"";
"Nein";"12.12.2018";"11.12.2018";"DESCRIPTION";"-50,00";"";
"Nein";"12.12.2018";"11.12.2018";"DESCRIPTION";"-10,00";"";
```

**Comment by JC5** [comment]
Sorry, they should really export valid CSV instead.

**Comment by joshwapohlmann** [comment]
Ok

**Comment by joshwapohlmann** [comment]
Ok

**Comment by Loxeno** [comment]
Hi,

I'm interested in a function like this too.
My bank does not provide a valid csv file...
I can't ask them to provide valid csv (they will recommend CFONB format, which is not possible for personal banking).

I have multiple header lines and a footer lines to skip.
I think this can been done with an option like this :
```
{
    ...
    "skip-first-lines": [
        1,
        2,
        3
     ]
    "skip-last-lines": [
        1
    ]
    ...
}
```

By advance, thank you !
